# Generated by Django 5.2.3 on 2025-06-27 22:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['-votes', 'choice_text'], 'verbose_name': 'Choice Option', 'verbose_name_plural': 'Choice Options'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Poll Question', 'verbose_name_plural': 'Poll Questions'},
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(help_text='Enter a clear choice option (2-200 characters)', max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Choice must be at least 2 characters long.')]),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='polls.question'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='votes',
            field=models.IntegerField(default=0, help_text='Number of votes this choice has received'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(help_text='When this question should be published', verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(help_text='Enter a clear, concise question (10-200 characters)', max_length=200, validators=[django.core.validators.MinLengthValidator(10, 'Question must be at least 10 characters long.')]),
        ),
        migrations.AlterUniqueTogether(
            name='choice',
            unique_together={('question', 'choice_text')},
        ),
    ]
